### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by arajasek** [zhike-aion/ABIGenerator#10]
We need to improve the testing of this tool. This involves a few things, in decreasing order of importance:

1. Most importantly, we need to write tests with various invalid inputs and improve our response to these inputs. This includes things like missing method name, wrong number of arguments, wrong types of arguments, surprising null params, etc.

2. Writing new tests with expected input. Perhaps we can leverage some of the existing `AVM` tests for this.

3. Improving the overall feel of our testing folder - move tests around, rename some test contracts, delete unnecessary ones.

**Comment by zhikezhang** [comment]
For 2, we may create dapp classes by code.  The number of methods, the number of arguments, the argument type could all be randomly created. 
Then, we deploy those dapps and verity the result.

**Comment by zhikezhang** [comment]
For 1, I guess we can put those error handlings and error messages in AVM core or runtime. AVM's already done some, but it's not perfect enough.
ABIGenerator only got the error messages from AVM and show them to a user.
