### ISSUE TITLE
Public static methods in non-main classes are not valid entry points

### ISSUE THREAD

**Issue by arajasek** [zhike-aion/ABIGenerator#7]
Per the title, we currently have a major overcomplication in the ABI generator. Since non-main classes cannot have valid entry points, and never need a `main()` generated, there's almost no work that ever needs to be done when visiting non-main classes. This brings up the following issues

1. We currently have a bug, because our generated ABI includes all `@Callable public` methods from non-main classes as Callable.

2. We can greatly simplify our `compile` process by not bothering to visit non-main classes. We might _not_ want to do this for 2 reasons:

- We can still do some useful analysis (rejecting non-main classes with `Callable` annotations or `main()` methods.
- There may be future utility in processing all classes, not just the main class.

EDIT: We should also confirm that `public`, but non-`static` methods are NOT valid entry points, even in the main class, and so should not have `@Callable` annotations.
EDIT2: Should we strip out the @Callable annotations in the generated class?

**Comment by zhikezhang** [comment]
Done.
